version: '3.3'

services:
   mysql:
     image: mysql:5.7
     volumes:
       - wp_db_data:/var/lib/mysql
     restart: always
     ports:
       - '3309:3306'
     environment:
       MYSQL_ROOT_PASSWORD: 'root'
       MYSQL_DATABASE: 'test-database'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: 'user'
volumes:
    wp_db_data: